gnu: nix: Update to 2.22.4.
* gnu/packages/package-management.scm (nix): Update to 2.22.4.
[arguments]{phases}: Adapt phase 'skip-failing-tests.
* gnu/packages/patches/nix-dont-build-html-doc.diff: Update accordingly.

Change-Id: I2f71cfcfd918d03e872671e0d948831c46b55b77

diff --git a/gnu/packages/patches/nix-dont-build-html-doc.diff b/gnu/packages/patches/nix-dont-build-html-doc.diff
--- a/gnu/packages/patches/nix-dont-build-html-doc.diff
+++ b/gnu/packages/patches/nix-dont-build-html-doc.diff
@@ -5,19 +5,29 @@ Author: Zhu Zihao <all_but_last@163.com>
 
 --- a/doc/manual/local.mk
 +++ b/doc/manual/local.mk
-@@ -172,11 +172,6 @@ $(d)/src/SUMMARY-rl-next.md: $(d)/src/release-notes/rl-next.md
+@@ -172,21 +172,6 @@ $(d)/src/SUMMARY-rl-next.md: $(d)/src/release-notes/rl-next.md
  	  true > $@; \
  	fi
  
 -# Generate the HTML manual.
 -.PHONY: manual-html
 -manual-html: $(docdir)/manual/index.html
+-
+-# Open the built HTML manual in the default browser.
+-manual-html-open: $(docdir)/manual/index.html
+-	@echo "  OPEN  " $<; \
+-	  xdg-open $< \
+-		  || open $< \
+-			|| { \
+-		echo "Could not open the manual in a browser. Please open '$<'" >&2; \
+-		false; \
+-		}
 -install: $(docdir)/manual/index.html
 -
  # Generate 'nix' manpages.
  .PHONY: manpages
  manpages: $(mandir)/man1/nix3-manpages
-@@ -202,26 +197,3 @@ doc/manual/generated/man1/nix3-manpages: $(d)/src/command-ref/new-cli
+@@ -212,26 +197,3 @@ doc/manual/generated/man1/nix3-manpages: $(d)/src/command-ref/new-cli
  		rm $$tmpFile; \
  	done
  	@touch $@
@@ -26,7 +36,7 @@ Author: Zhu Zihao <all_but_last@163.com>
 -# `@docroot@` is to be preserved for documenting the mechanism
 -# FIXME: maybe contributing guides should live right next to the code
 -# instead of in the manual
--$(docdir)/manual/index.html: $(MANUAL_SRCS) $(d)/book.toml $(d)/anchors.jq $(d)/custom.css $(d)/src/SUMMARY.md $(d)/src/store/types $(d)/src/command-ref/new-cli $(d)/src/contributing/experimental-feature-descriptions.md $(d)/src/command-ref/conf-file.md $(d)/src/language/builtins.md $(d)/src/language/builtin-constants.md $(d)/src/release-notes/rl-next.md
+-$(docdir)/manual/index.html: $(MANUAL_SRCS) $(d)/book.toml $(d)/anchors.jq $(d)/custom.css $(d)/src/SUMMARY.md $(d)/src/store/types $(d)/src/command-ref/new-cli $(d)/src/contributing/experimental-feature-descriptions.md $(d)/src/command-ref/conf-file.md $(d)/src/language/builtins.md $(d)/src/language/builtin-constants.md $(d)/src/release-notes/rl-next.md $(d)/src/figures $(d)/src/favicon.png $(d)/src/favicon.svg
 -	$(trace-gen) \
 -		tmp="$$(mktemp -d)"; \
 -		cp -r doc/manual "$$tmp"; \
